import Customer from "./Customer";

export { default as Ecommerce } from "./Ecommerce";
export { default as InProgress } from "./InProgress";
export { default as Orders } from "./Orders";
export { default as Employee } from "./Employee";
export { default as Customer } from "./Customer";
export { default as Calendar } from "./Calendar";
export { default as Kanban } from "./Kanban";
export { default as Editor } from "./Editor";
export { default as ColorPicker } from "./ColorPicker";
export { default as Line } from "./Chart/Line";
export { default as Area } from "./Chart/Area";
export { default as Bar } from "./Chart/Bar";
export { default as Pie } from "./Chart/Pie";
export { default as Financial } from "./Chart/Financial";
export { default as ColorMapping } from "./Chart/ColorMapping";
export { default as Pyramid } from "./Chart/Pyramid";
export { default as Stacked } from "./Chart/Stacked";
export { default as Loading } from "./Loading";
export { default as LazyComponent } from "./LazyComponent";
